site:
  title: Michael Samoylenko - Personal Website
  url: https://samoylenko.me
  start_page: site::index.adoc
content:
  sources:
    - url: .
      start_path: site
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''

ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
