name: Lint

on: [push]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: npm install

      - name: Lint Markdown
        run: npm run lint-md

      - name: Proofread
        run: npm run proofread
